/** '바로가기' 탭 — _tools/make_links_gs.js 가 만든 파일. 고치지 말고 다시 만든다. */
var LINKS_VER = '2026-10-03-62';
var LINKS = [["교사","","교사용 허브(전 과목)","","https://wmfsljy-coder.github.io/science-teacher-hub/"],
  ["교사","","반별 활동 · 수업 효과 · 모둠 편성","","https://wmfsljy-coder.github.io/science-teacher-hub/class/"],
  ["과목","1학년","통합과학","(과목 첫 화면)","https://wmfsljy-coder.github.io/integrated-science/"],
  ["과목","1학년","통합과학1","(단원 목록)","https://wmfsljy-coder.github.io/integrated-science-1/"],
  ["단원","1학년","통합과학1","1-1 과학의 기본량","https://wmfsljy-coder.github.io/integrated-science-1/1-1/"],
  ["단원","1학년","통합과학1","1-2 과학의 측정과 우리 사회","https://wmfsljy-coder.github.io/integrated-science-1/1-2/"],
  ["단원","1학년","통합과학1","2-1 자연의 구성 원소","https://wmfsljy-coder.github.io/integrated-science-1/2-1/"],
  ["단원","1학년","통합과학1","2-2 물질의 규칙성과 성질","https://wmfsljy-coder.github.io/integrated-science-1/2-2/"],
  ["단원","1학년","통합과학1","3-1 지구시스템","https://wmfsljy-coder.github.io/integrated-science-1/3-1/"],
  ["단원","1학년","통합과학1","3-2 역학 시스템","https://wmfsljy-coder.github.io/integrated-science-1/3-2/"],
  ["단원","1학년","통합과학1","3-3 생명 시스템","https://wmfsljy-coder.github.io/integrated-science-1/3-3/"],
  ["과목","1학년","통합과학2","(단원 목록)","https://wmfsljy-coder.github.io/integrated-science-2/"],
  ["단원","1학년","통합과학2","1-1 지구 환경 변화와 생물다양성","https://wmfsljy-coder.github.io/integrated-science-2/1-1/"],
  ["단원","1학년","통합과학2","1-2 화학 변화","https://wmfsljy-coder.github.io/integrated-science-2/1-2/"],
  ["단원","1학년","통합과학2","2-1 생태계와 환경 변화","https://wmfsljy-coder.github.io/integrated-science-2/2-1/"],
  ["단원","1학년","통합과학2","2-2 에너지 전환과 활용","https://wmfsljy-coder.github.io/integrated-science-2/2-2/"],
  ["단원","1학년","통합과학2","3-1 과학 기술의 활용","https://wmfsljy-coder.github.io/integrated-science-2/3-1/"],
  ["단원","1학년","통합과학2","3-2 과학 기술의 발전과 쟁점","https://wmfsljy-coder.github.io/integrated-science-2/3-2/"],
  ["과목","1학년","과학탐구실험","(과목 첫 화면)","https://wmfsljy-coder.github.io/science-inquiry/"],
  ["과목","1학년","과학탐구실험1","(단원 목록)","https://wmfsljy-coder.github.io/science-inquiry-1/"],
  ["단원","1학년","과학탐구실험1","1-1 과학의 본성과 역사 속의 과학 탐구","https://wmfsljy-coder.github.io/science-inquiry-1/1-1/"],
  ["단원","1학년","과학탐구실험1","1-2 과학 탐구의 과정과 절차","https://wmfsljy-coder.github.io/science-inquiry-1/1-2/"],
  ["단원","1학년","과학탐구실험1","1-3 과학의 본성과 역사 속의 과학 탐구","https://wmfsljy-coder.github.io/science-inquiry-1/1-3/"],
  ["단원","1학년","과학탐구실험1","1-4 과학 탐구의 과정과 절차","https://wmfsljy-coder.github.io/science-inquiry-1/1-4/"],
  ["과목","1학년","과학탐구실험2","(단원 목록)","https://wmfsljy-coder.github.io/science-inquiry-2/"],
  ["단원","1학년","과학탐구실험2","2-1 생활 속의 과학 탐구","https://wmfsljy-coder.github.io/science-inquiry-2/2-1/"],
  ["단원","1학년","과학탐구실험2","2-2 미래 사회와 첨단 과학 탐구","https://wmfsljy-coder.github.io/science-inquiry-2/2-2/"],
  ["단원","1학년","과학탐구실험2","2-3 생활 속의 과학 탐구","https://wmfsljy-coder.github.io/science-inquiry-2/2-3/"],
  ["단원","1학년","과학탐구실험2","2-4 미래 사회와 첨단 과학 탐구","https://wmfsljy-coder.github.io/science-inquiry-2/2-4/"],
  ["과목","2학년","지구과학","(단원 목록)","https://wmfsljy-coder.github.io/earth-science-2/"],
  ["단원","2학년","지구과학","1-1 해수의 순환과 대기의 변화","https://wmfsljy-coder.github.io/earth-science-2/1-1/"],
  ["단원","2학년","지구과학","1-2 대기와 해양의 상호작용과 기후 변화","https://wmfsljy-coder.github.io/earth-science-2/1-2/"],
  ["단원","2학년","지구과학","2-1 지구의 역사","https://wmfsljy-coder.github.io/earth-science-2/2-1/"],
  ["단원","2학년","지구과학","2-2 한반도의 암석","https://wmfsljy-coder.github.io/earth-science-2/2-2/"],
  ["단원","2학년","지구과학","3-1 태양계 행성의 겉보기 운동","https://wmfsljy-coder.github.io/earth-science-2/3-1/"],
  ["단원","2학년","지구과학","3-2 별과 우주의 진화","https://wmfsljy-coder.github.io/earth-science-2/3-2/"],
  ["과목","2학년","지구시스템과학","(과목 첫 화면)","https://wmfsljy-coder.github.io/earth-system/"],
  ["과목","2학년","지구시스템과학1","(단원 목록)","https://wmfsljy-coder.github.io/earth-system-1/"],
  ["단원","2학년","지구시스템과학1","1-1 지구의 탄생과 진화","https://wmfsljy-coder.github.io/earth-system-1/1-1/"],
  ["단원","2학년","지구시스템과학1","1-2 판 구조 운동과 지구 내부 구조","https://wmfsljy-coder.github.io/earth-system-1/1-2/"],
  ["과목","2학년","지구시스템과학2","(단원 목록)","https://wmfsljy-coder.github.io/earth-system-2/"],
  ["단원","2학년","지구시스템과학2","2-1 해수의 운동","https://wmfsljy-coder.github.io/earth-system-2/2-1/"],
  ["단원","2학년","지구시스템과학2","2-2 강수 과정과 대기의 운동","https://wmfsljy-coder.github.io/earth-system-2/2-2/"],
  ["과목","2학년","행성우주과학","(과목 첫 화면)","https://wmfsljy-coder.github.io/planet-space/"],
  ["과목","2학년","행성우주과학1","(단원 목록)","https://wmfsljy-coder.github.io/planet-space-1/"],
  ["단원","2학년","행성우주과학1","1-1 우주 탐사와 태양 활동","https://wmfsljy-coder.github.io/planet-space-1/1-1/"],
  ["단원","2학년","행성우주과학1","1-2 태양계 천체와 외계 행성","https://wmfsljy-coder.github.io/planet-space-1/1-2/"],
  ["과목","2학년","행성우주과학2","(단원 목록)","https://wmfsljy-coder.github.io/planet-space-2/"],
  ["단원","2학년","행성우주과학2","2-1 태양과 별의 관측","https://wmfsljy-coder.github.io/planet-space-2/2-1/"],
  ["단원","2학년","행성우주과학2","2-2 은하와 우주","https://wmfsljy-coder.github.io/planet-space-2/2-2/"],
  ["과목","2학년","기후변화와 환경생태","(단원 목록)","https://wmfsljy-coder.github.io/climate-change-ecology/"],
  ["단원","2학년","기후변화와 환경생태","1 기후와 환경생태의 특성","https://wmfsljy-coder.github.io/climate-change-ecology/1/"],
  ["단원","2학년","기후변화와 환경생태","2 기후위기와 환경생태 변화","https://wmfsljy-coder.github.io/climate-change-ecology/2/"],
  ["단원","2학년","기후변화와 환경생태","3 기후위기에 대응하는 우리의 노력","https://wmfsljy-coder.github.io/climate-change-ecology/3/"],
  ["과목","2학년","융합과학 탐구","(단원 목록)","https://wmfsljy-coder.github.io/convergence-science-inquiry/"],
  ["단원","2학년","융합과학 탐구","1 융합과학 탐구의 이해","https://wmfsljy-coder.github.io/convergence-science-inquiry/1/"],
  ["단원","2학년","융합과학 탐구","2 융합과학 탐구의 과정","https://wmfsljy-coder.github.io/convergence-science-inquiry/2/"],
  ["단원","2학년","융합과학 탐구","3 융합과학 탐구의 전망","https://wmfsljy-coder.github.io/convergence-science-inquiry/3/"],
  ["과목","2학년","과학의 역사와 문화","(단원 목록)","https://wmfsljy-coder.github.io/science-history-culture/"],
  ["단원","2학년","과학의 역사와 문화","1 과학과 문명의 탄생과 통합","https://wmfsljy-coder.github.io/science-history-culture/1/"],
  ["단원","2학년","과학의 역사와 문화","2 변화하는 과학과 세계","https://wmfsljy-coder.github.io/science-history-culture/2/"],
  ["단원","2학년","과학의 역사와 문화","3 과학과 인류의 미래","https://wmfsljy-coder.github.io/science-history-culture/3/"]];
